# Generated by Django 5.2.4 on 2025-09-28 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewlink',
            name='created_at',
        ),
    ]
