# Generated by Django 5.2.4 on 2025-09-28 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_remove_reviewlink_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerreview',
            name='ai_review',
        ),
        migrations.RemoveField(
            model_name='customerreview',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='customerreview',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='customerreview',
            name='status',
        ),
    ]
