# Generated by Django 5.2.4 on 2025-08-10 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_user_stripe_customer_id_user_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_end_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_plan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_start_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trial_end_date',
        ),
    ]
