# Generated by Django 5.2.4 on 2025-09-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_remove_customerreview_ai_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='ai_review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerreview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
