# Generated by Django 5.2.4 on 2025-10-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_customerreview_ai_review_customerreview_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='total_reviews',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
