# Generated by Django 5.2.4 on 2025-10-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_business_rating_business_total_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
